name: Workflow for lowell-mat_examples CODECOV
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
        
    - name: CREATE COVERAGE report
      run: |
        pip install wheel 
        pip install pytest
        pip install pytest-cov
        pip install git+https://github.com/LowellInstruments/bluepy.git
        pip install git+https://github.com/LowellInstruments/lowell-mat.git
        pytest --cov=./ tests/ --cov-report=xml
        
    - name: UPLOAD COVERAGE report to COVECOD
      uses: codecov/codecov-action@v2
      with:
      
        # only private repositories need TOKEN
        # token: ${{ secrets.CODECOV_TOKEN }}
        
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
